#!/bin/sh
# One-shot boot tasks. Keep it fast.
cmdline=$(cat /proc/cmdline)

case "$cmdline" in
  *muslin.selftest*) ;;
  *)
    (
      ifconfig lo up
      ifconfig eth0 up
      udhcpc -i eth0 -q -n -s /etc/udhcpc.script
      exec muslin-go serve
    ) >/dev/console 2>&1 &
    ;;
esac

case "$cmdline" in
  *muslin.selftest*)
    ls / >/dev/null &&
      cat /etc/hostname >/dev/null &&
      ps >/dev/null &&
      dmesg >/dev/null &&
      muslin-go &&
      echo MUSLIN_USERLAND_OK
    ;;
esac
