#!/bin/sh
# One-shot boot tasks. Keep it fast.
cmdline=$(cat /proc/cmdline)

case "$cmdline" in
  *muslin.postgres*)
    if [ ! -f /var/lib/mpkg/postgresql/manifest ]; then
      mpkg install /var/lib/muslin/postgresql.mpkg || exit 1
    fi
    /etc/init.d/postgresql start || exit 1
    echo MUSLIN_POSTGRES_READY
    ;;
esac

case "$cmdline" in
  *muslin.selftest*|*muslin.persisttest*|*muslin.packagetest*|*muslin.acceptance*) ;;
  *)
    (
      ifconfig lo up
      ifconfig eth0 up
      udhcpc -i eth0 -q -n -s /etc/udhcpc.script
      exec muslin-go serve
    ) >/dev/console 2>&1 &
    ;;
esac

case "$cmdline" in
  *muslin.packagetest*)
    mpkg install /var/lib/muslin/test.mpkg /var/lib/muslin/test.mpkg.sha256 &&
      /usr/bin/muslin-hello
    ;;
esac

case "$cmdline" in
  *muslin.selftest*)
    ls / >/dev/null &&
      cat /etc/hostname >/dev/null &&
      ps >/dev/null &&
      dmesg >/dev/null &&
      muslin-go &&
      echo MUSLIN_USERLAND_OK
    ;;
esac
